<option value="" selected disabled>Solo interni</option>
<option value="1">1a Anestesia e rianimazione</option>
<option value="2">2a Anestesia, rianimazione e terapia antalgica</option>
<option value="3">Anatomia e istologia patologica</option>
<option value="4">Biochimica a elevata automazione</option>
<option value="5">Cardiochirurgia</option>
<option value="6">Cardiologia</option>
<option value="7">Cardiologia pediatrica</option>
<option value="8">Centrale operativa 118 – Elisoccorso Area Omogenea Emilia Ovest</option>
<option value="9">Centro hub Emofilia e malattie emorragiche congenite</option>
<option value="10">Chirurgia d’urgenza</option>
<option value="11">Chirurgia della cute e annessi, mininvasiva, rigenerativa e plastica</option>
<option value="12">Chirurgia pediatrica</option>
<option value="13">Chirurgia plastica e Centro ustioni</option>
<option value="14">Chirurgia toracica</option>
<option value="15">Chirurgia vascolare</option>
<option value="16">Clinica chirurgica generale</option>
<option value="17">Clinica e immunologia medica</option>
<option value="18">Clinica e terapia medica</option>
<option value="19">Clinica geriatrica</option>
<option value="20">Clinica ortopedica</option>
<option value="21">Clinica pediatrica</option>
<option value="22">Clinica pneumologica</option>
<option value="23">Coordinamento attività specialistiche ambulatoriali cardiologiche</option>
<option value="24">Day hospital dipartimentale</option>
<option value="25">Day hospital pneumologico</option>
<option value="26">Degenza breve – week hospital</option>
<option value="27">Dermatologia</option>
<option value="28">Diagnostica ematochimica</option>
<option value="29">Dipartimento Chirurgico generale e Specialistico</option>
<option value="30">Dipartimento Diagnostico</option>
<option value="31">Dipartimento Emergenza-Urgenza e Area Medica Generale e Specialistica</option>
<option value="32">Dipartimento Materno Infantile</option>
<option value="33">Dipartimento Medico Geriatrico Riabilitativo</option>
<option value="34">Ematologia e Centro trapianti midollo osseo (Ctmo)</option>
<option value="35">Endocrinologia e Malattie del metabolismo</option>
<option value="36">Funzionalità polmonare</option>
<option value="37">Gastroenterologia ed endoscopia digestiva</option>
<option value="38">Genetica medica</option>
<option value="39">Geriatria</option>
<option value="40">Immunoematologia e trasfusionale</option>
<option value="41">Malattie del ricambio e diabetologia</option>
<option value="42">Malattie infettive ed epatologia</option>
<option value="43">Maxillo-facciale</option>
<option value="44">Medicina del lavoro e tossicologia industriale</option>
<option value="45">Medicina interna</option>
<option value="46">Medicina interna a indirizzo angiologico e coagulativo</option>
<option value="47">Medicina interna e Lungodegenza critica</option>
<option value="48">Medicina nucleare</option>
<option value="49">Medicina riabilitativa</option>
<option value="50">Microbiologia</option>
<option value="51">Nefrologia</option>
<option value="52">Neonatologia</option>
<option value="53">Neurochirurgia</option>
<option value="54">Neurologia</option>
<option value="55">Neuroradiologia</option>
<option value="56">Oculistica</option>
<option value="57">Odontostomatologia</option>
<option value="58">Oncologia medica</option>
<option value="59">Ostetricia e ginecologia</option>
<option value="60">Otorinolaringoiatria e otoneurochirurgia</option>
<option value="61">Pediatria e oncoematologia</option>
<option value="62">Pediatria Generale e d’Urgenza</option>
<option value="63">Pneumologia ed endoscopia toracica</option>
<option value="64">Polo Emergenza-urgenza</option>
<option value="65">Pronto soccorso e medicina d’urgenza</option>
<option value="66">Radiologia</option>
<option value="67">Radiologia pediatrica</option>
<option value="68">Radioterapia</option>
<option value="69">Scienze radiologiche</option>
<option value="70">Trapianti di midollo osseo e cellule staminali emopoietiche</option>
<option value="71">Urologia</option>
<option value="72">Virologia</option>
