<option value="1">ANGIO RM DELL'ADDOME INFERIORE</option>
<option value="2">ANGIO- RM DEL DISTRETTO TORACICO</option>
<option value="3">ANGIO- RM DEL DISTRETTO VASCOLARE INTRACRANICO</option>
<option value="4">ANGIO-RM DELL' ARTO SUPERIORE O INFERIORE</option>
<option value="5">ANGIO-RM DELL'ARTO INFERIORE DX </option>
<option value="6">ANGIO-RM DELL'ARTO INFERIORE SX </option>
<option value="7">ANGIO-RM DELL'ARTO SUPERIORE DX </option>
<option value="8">ANGIO-RM DELL'ARTO SUPERIORE SX </option>
<option value="9">RM DEL CERVELLO E DEL TRONCO ENCEFALICO</option>
<option value="10">RM DEL CERVELLO E DEL TRONCO ENCEFALICO, SENZA E CON CONTRASTO</option>
<option value="11">RM DEL COLLO</option>
<option value="12">RM DEL COLLO, SENZA E CON CONTRASTO</option>
<option value="13">RM DEL CUORE</option>
<option value="14">RM DEL CUORE, SENZA E CON CONTRASTO</option>
<option value="15">RM DEL MASSICCIO FACCIALE</option>
<option value="16">RM DEL MASSICCIO FACCIALE, SENZA E CON CONTRASTO</option>
<option value="17">RM DEL TORACE</option>
<option value="18">RM DEL TORACE, SENZA E CON CONTRASTO</option>
<option value="19">RM DELL'ADDOME INFERIORE E SCAVO PELVICO</option>
<option value="20">RM DELL'ADDOME INFERIORE E SCAVO PELVICO, SENZA E CON CONTRASTO</option>
<option value="21">RM DELL'ADDOME SUPERIORE</option>
<option value="22">RM DELL'ADDOME SUPERIORE, SENZA E CON CONTRASTO</option>
<option value="23">RM DELLA COLONNA</option>
<option value="24">RM DELLA COLONNA, SENZA E CON CONTRASTO</option>
<option value="25">RM DELLA MAMMELLA</option>
<option value="26">RM DELLA MAMMELLA BILATERALE</option>
<option value="27">RM DELLA MAMMELLA, SENZA E CON CONTRASTO BILATERALE</option>
<option value="28">RM DELLA MAMMELLA, SENZA E CON CONTRASTO MONOLATERALE</option>
<option value="29">RM MUSCOLOSCHELETRICA</option>
<option value="30">RM MUSCOLOSCHELETRICA, SENZA E CON CONTRASTO</option>
<option value="31">RISONANZA MAGNETICA NUCLEARE (CINE-RM) DEL CUORE </option>
