<option value="1">ALTRA RADIOGRAFIA DENTARIA</option>
<option value="2">RADIOGRAFIA ADDOME</option>
<option value="3">RADIOGRAFIA ASSIALE DELLA ROTULA</option>
<option value="4">RADIOGRAFIA COLONNA CERVICALE</option>
<option value="5">RADIOGRAFIA COLONNA TORACICA (DORSALE)</option>
<option value="6">RADIOGRAFIA COMPLETA DEGLI ARTI INFERIORI E DEL BACINO SOTTO CARICO</option>
<option value="7">RADIOGRAFIA COMPLETA DEL TUBO DIGERENTE</option>
<option value="8">RADIOGRAFIA CON CONTRASTO DELLE GHIANDOLE SALIVARI</option>
<option value="9">RADIOGRAFIA COSTE-STERNO-CLAVICOLA BILATERALE</option>
<option value="10">RADIOGRAFIA DEI TESSUTI MOLLI DELLA FACCIA, DEL CAPO E DEL COLLO</option>
<option value="11">RADIOGRAFIA DEL CRANIO E SENI PARANASALI</option>
<option value="12">RADIOGRAFIA DEL PANCREAS CON CONTRASTO</option>
<option value="13">RADIOGRAFIA DEL TORACE DI ROUTINE, NAS</option>
<option value="14">RADIOGRAFIA DEL TRATTO FARINGO-CRICO-ESOFAGEO-CARDIALE</option>
<option value="15">RADIOGRAFIA DEL TRATTO GASTROINTESTINALE INFERIORE</option>
<option value="16">RADIOGRAFIA DEL TRATTO GASTROINTESTINALE SUPERIORE</option>
<option value="17">RADIOGRAFIA DELL'APPARATO URINARIO</option>
<option value="18">RADIOGRAFIA DELL'ESOFAGO CON DOPPIO CONTRASTO </option>
<option value="19">RADIOGRAFIA DELLA SELLA TURCICA</option>
<option value="20">RADIOGRAFIA DELLA TRACHEA</option>
<option value="21">RADIOGRAFIA DELLO SCHELETRO IN TOTO</option>
<option value="22">RADIOGRAFIA DELLO STOMACO E DEL DUODENO CON DOPPIO CONTRASTO</option>
<option value="23">RADIOGRAFIA ESOFAGO CON CONTRASTO</option>
<option value="24">ALTRA RADIOGRAFIA DI OSSA DELLA FACCIA</option>
<option value="25">RADIOGRAFIA ARCATA DENTARIA SUP. O INF.</option>
<option value="26">RADIOGRAFIA COLONNA LOMBOSACRALE</option>
<option value="27">RADIOGRAFIA COMPLETA DEL LATTANTE</option>
<option value="28">RADIOGRAFIA CON OCCLUSALE DI ARCATA DENTARIA INFERIORE</option>
<option value="29">RADIOGRAFIA CON OCCLUSALE DI ARCATA DENTARIA SUPERIORE</option>
<option value="30">RADIOGRAFIA CON OCCLUSALE DI ARCATA DENTARIA</option>
<option value="31">RADIOGRAFIA COSTE-STERNO-CLAVIC .2 PROIEZ.</option>
<option value="32">RADIOGRAFIA DEL FEMORE, GINOCCHIO E GAMBA</option>
<option value="33">RADIOGRAFIA DEL POLSO E DELLA MANO</option>
<option value="34">RADIOGRAFIA DI PELVI E ANCA</option>
<option value="35">RADIOGRAFIA GOMITO E AVAMBRACCIO</option>
<option value="36">RADIOGRAFIA PIEDE E CAVIGLIA</option>
<option value="37">RADIOGRAFIA SPALLA E ARTO SUPERIORE</option>
<option value="38">TELERADIOGRAFIA DEL CRANIO</option>
<option value="39">RX ANCA DX </option>
<option value="40">RX ANCA SX </option>
<option value="41">RX ARTICOLAZIONI SACRO ILIACHE </option>
<option value="42">RX COMPLETA DELLA COLONNA</option>
<option value="43">RX DEL BACINO </option>
<option value="44">RX DEL BRACCIO DX </option>
<option value="45">RX DEL BRACCIO SX </option>
<option value="46">RX DEL DITO DELLA MANO DX </option>
<option value="47">RX DEL DITO DELLA MANO SX</option>
<option value="48">RX DEL FEMORE DX </option>
<option value="49">RX DEL FEMORE SX </option>
<option value="50">RX DEL GINOCCHIO DX </option>
<option value="51">RX DEL GINOCCHIO SX </option>
<option value="52">RX DEL GOMITO DX </option>
<option value="53">RX DEL GOMITO SX</option>
<option value="54">RX DEL MASTOIDE (INCLUDE ROCCHE PETROSE, FORAMI OTTICI) </option>
<option value="55">RX DEL PIEDE DX </option>
<option value="56">RX DEL PIEDE SX </option>
<option value="57">RX DEL POLSO DX </option>
<option value="58">RX DEL POLSO SX </option>
<option value="59">RX DEL RACHIDE LOMBOSACRALE </option>
<option value="60">RX DEL RACHIDE SACROCOCCIGEO </option>
<option value="61">RX DELL'ARCATA DENTARIA INFERIORE </option>
<option value="62">RX DELL'ARCATA DENTARIA SUPERIORE </option>
<option value="63">RX DELL'ARTICOLAZIONE TEMPORO MANDIBOLARE DX </option>
<option value="64">RX DELL'ARTICOLAZIONE TEMPORO MANDIBOLARE SX </option>
<option value="65">RX DELL'AVAMBRACCIO DX </option>
<option value="66">RX DELL'AVAMBRACCIO SX </option>
<option value="67">RX DELL'EMITORACE DX PER COSTE </option>
<option value="68">RX DELL'EMITORACE SX PER COSTE </option>
<option value="69">RX DELLA CAVIGLIA DX </option>
<option value="70">RX DELLA CAVIGLIA SX </option>
<option value="71">RX DELLA CLAVICOLA DX </option>
<option value="72">RX DELLA CLAVICOLA SX </option>
<option value="73">RX DELLA GAMBA DX </option>
<option value="74">RX DELLA GAMBA SX </option>
<option value="75">RX DELLA MANO DX </option>
<option value="76">RX DELLA MANO SX </option>
<option value="77">RX DELLA SPALLA DX </option>
<option value="78">RX DELLA SPALLA SX </option>
<option value="79">RX DELLE ORBITE </option>
<option value="80">RX DELLE OSSA NASALI </option>
<option value="81">RX DELLO STERNO </option>
<option value="82">RX EMIMANDIBOLA DX </option>
<option value="83">RX EMIMANDIBOLA SX </option>
<option value="84">RX TORACO-BRACHIALE </option>
