<option value="" selected disabled>scegli un SDO</option>
<option value="	01	">	01 - dimesso a casa o auto-cura (dimissione di routine)	</option>
<option value="	02	">	02 - dimesso / trasferito a un ospedale generale a breve termine per cure ospedaliere	</option>
<option value="	03	">	03 - dimesso / trasferimento a un centro di assistenza infermieristica qualificato (SNF) con certificazione Medicare in previsione di assistenza qualificata	</option>
<option value="	04	">	04 - dimesso / trasferito in una struttura che fornisce assistenza di custodia o di supporto	</option>
<option value="	05	">	05 - dimesso / trasferito in un Designated Cancer Center o Children's Hospital	</option>
<option value="	06	">	06 - dimesso / trasferito a una casa sotto cura di un'organizzazione di servizi sanitari domiciliari organizzata in previsione di assistenza qualificata	</option>
<option value="	07	">	07 - Left Against Medical Advice (AMA) o cure cessate	</option>
<option value="	08	">	09 - Ammesso come ricoverato in questo ospedale	</option>
<option value="	20	">	20 - Deceduto (morto)	</option>
<option value="	21	">	21 - Congedato / trasferito alla Corte / Applicazione della legge	</option>
<option value="	30	">	30 - Ancora paziente	</option>
<option value="	40	">	40 - Deceduto a casa	</option>
<option value="	41	">	41 - Deceduto in una struttura medica (ad es. Ospedale, SNF, ICF o ospizio indipendente)	</option>
<option value="	42	">	42 - Deceduto - luogo sconosciuto	</option>
<option value="	43	">	43 - dimesso / trasferito a un centro sanitario federale	</option>
<option value="	50	">	50 - ospizio - Home	</option>
<option value="	51	">	51 - ospizio - Medical Facility (certificato) che fornisce il livello di assistenza ospizio	</option>
<option value="	61	">	61 - dimesso / trasferimento a un letto basculante approvato dall'ospedale Medicare	</option>
<option value="	62	">	62 - dimesso / trasferito a una struttura di riabilitazione ospedaliera (IRF) Compresa la riabilitazione delle parti distinte di un ospedale	</option>
<option value="	63	">	63 - dimesso / trasferito a un ospedale per cure a lungo termine certificato da Medicare (LTCH)	</option>
<option value="	64	">	64 - dimesso / trasferito in una struttura di cura certificata da Medicaid ma non certificata da Medicare	</option>
<option value="	65	">	65 - dimesso / trasferito in un ospedale psichiatrico o in una parte distinta psichiatrica di un ospedale	</option>
<option value="	66	">	66 - dimesso / trasferito in un ospedale ad accesso critico (CAH)	</option>
<option value="	69	">	69 - dimesso / trasferito in un sito di assistenza alternativa per disastri designato	</option>
<option value="	70	">	70 - dimesso / trasferito a un altro tipo di istituto sanitario non definito altrove in questo elenco di codici	</option>
<option value="	81	">	81 - dimesso / trasferito a domicilio o autosufficiente con la riammissione ospedaliera di ricovero ospedaliero in terapia acuta programmata	</option>
<option value="	82	">	82 - dimesso / trasferito in un ospedale a breve termine con riammissione ospedaliera di ricovero ospedaliero programmato	</option>
<option value="	83	">	83 - Congedato / trasferito a un centro di assistenza infermieristica qualificato (SNF) con certificazione Medicare con riammissione ospedaliera di ricovero ospedaliero per terapia intensiva programmata	</option>
<option value="	84	">	84 - dimesso / trasferito in una struttura che fornisce assistenza di custodia o di supporto con la riammissione ospedaliera di pazienti ospedalizzati per terapia acuta programmata	</option>
<option value="	85	">	85 - dimesso / trasferimento a un centro per i tumori o un ospedale per bambini con ricovero ospedaliero programmato per riammissione acuta	</option>
<option value="	86	">	86 - dimesso / trasferito in una casa a cura dell'organizzazione organizzata di servizi sanitari a domicilio con riammissione ospedaliera programmata per degenza ospedaliera	</option>
<option value="	87	">	87 - Congedato / trasferito a un tribunale / Forze dell'ordine con riammissione ospedaliera in regime ospedaliero programmato	</option>
<option value="	88	">	88 - dimesso / trasferito a un centro sanitario federale con riammissione ospedaliera di ricovero ospedaliero di terapia acuta programmata	</option>
<option value="	89	">	89 - dimesso / trasferito a un letto basculante approvato dall'ospedale Medicare con riammissione ospedaliera programmata per degenza ospedaliera	</option>
<option value="	90	">	90 - dimesso / trasferito a una struttura di riabilitazione ospedaliera (IRF) inclusa la riabilitazione di unità distinte di un ospedale con ricovero ospedaliero di rianimazione ospedaliero programmato	</option>
<option value="	91	">	91 - dimesso / trasferito a un ospedale per cure a lungo termine certificato (LTCH) Medicare con riammissione ospedaliera ricoverata ospedaliera per terapia intensiva programmata	</option>
<option value="	92	">	92 - dimesso / trasferito in una struttura di cura certificata da Medicaid ma non certificata da Medicare con la riammissione ospedaliera in regime di ricovero ospedaliero programmato	</option>
<option value="	93	">	93 - dimesso / trasferito in un ospedale psichiatrico o in una parte distinta psichiatrica di un ospedale con ricovero ospedaliero di rianimazione ospedaliero programmato	</option>
<option value="	94	">	94 - dimesso / trasferito in un ospedale ad accesso critico (CAH) con la riammissione ospedaliera per pazienti ospedalizzati in terapia acuta programmata	</option>
<option value="	95	">	95 - dimesso / trasferito a un altro tipo di istituto di assistenza sanitaria non definito altrove in questo elenco di codici con la riammissione ospedaliera di pazienti ospedalizzati per terapia acuta programmata	</option>
