<option value="1">ARTRO TC GINOCCHIO DX </option>
<option value="2">ARTRO TC GINOCCHIO SX </option>
<option value="3">ARTRO TC GOMITO DX </option>
<option value="4">ARTRO TC GOMITO SX </option>
<option value="5">ARTRO TC SPALLA DX </option>
<option value="6">ARTRO TC SPALLA SX </option>
<option value="7">DENSITOMETRIA OSSEA CON TC LOMBARE</option>
<option value="8">TC ARTO SUP. CON E SENZA CONTRASTO</option>
<option value="9">TC ARTO SUPERIORE</option>
<option value="10">TC DEI RENI</option>
<option value="11">TC DEI RENI, SENZA E CON CONTRASTO</option>
<option value="12">TC DEL BACINO</option>
<option value="13">TC DEL CAPO</option>
<option value="14">TC DEL CAPO, SENZA E CON CONTRASTO</option>
<option value="15">TC DEL COLLO</option>
<option value="16">TC DEL COLLO, SENZA E CON CONTRASTO</option>
<option value="17">TC DEL CRANIO</option>
<option value="18">TC DEL CRANIO, SENZA E CON CONTRASTO </option>
<option value="19">TC DEL GOMITO-AVAMBRACCIO DX </option>
<option value="20">TC DEL GOMITO-AVAMBRACCIO DX, SENZA E CON CONTRASTO </option>
<option value="21">TC DEL GOMITO-AVAMBRACCIO SX </option>
<option value="22">TC DEL GOMITO-AVAMBRACCIO SX, SENZA E CON CONTRASTO </option>
<option value="23">TC DEL MASSICCIO FACCIALE</option>
<option value="24">TC DEL MASSICCIO FACCIALE, SENZA E CON CONTRASTO</option>
<option value="25">TC DEL POLSO-MANO DX </option>
<option value="26">TC DEL POLSO-MANO DX, SENZA E CON CONTRASTO </option>
<option value="27">TC DEL POLSO-MANO SX </option>
<option value="28">TC DEL POLSO-MANO SX, SENZA E CON CONTRASTO </option>
<option value="29">TC DEL RACHIDE E DELLO SPECO VERTEBRALE, SENZA E CON CONTRASTO</option>
<option value="30">TC DEL TORACE</option>
<option value="31">TC DEL TORACE, SENZA E CON CONTRASTO</option>
<option value="32">TC DELL' ADDOME COMPLETO</option>
<option value="33">TC DELL' ADDOME COMPLETO, SENZA E CON CONTRASTO</option>
<option value="34">TC DELL' ADDOME INFERIORE</option>
<option value="35">TC DELL' ADDOME INFERIORE, SENZA E CON CONTRASTO</option>
<option value="36">TC DELL' ADDOME SUPERIORE</option>
<option value="37">TC DELL' ADDOME SUPERIORE, SENZA E CON CONTRASTO</option>
<option value="38">TC DELL' ARTO INFERIORE</option>
<option value="39">TC DELL' ARTO INFERIORE, SENZA E CON CONTRASTO</option>
<option value="40">TC DELL' ORECCHIO</option>
<option value="41">TC DELL' ORECCHIO, SENZA E CON CONTRASTO</option>
<option value="42">TC DELL'ARCATA DENTARIA INFERIORE </option>
<option value="43">TC DELL'ARCATA DENTARIA SUPERIORE </option>
<option value="44">TC DELL'ARTO INFERIORE (ART. COXOFEMORALE, FEMORE) DX </option>
<option value="45">TC DELL'ARTO INFERIORE (ART. COXOFEMORALE, FEMORE) SX </option>
<option value="46">TC DELL'ARTO INFERIORE (CAVIGLIA PIEDE) DX </option>
<option value="47">TC DELL'ARTO INFERIORE (CAVIGLIA PIEDE) SX </option>
<option value="48">TC DELL'ARTO INFERIORE (GINOCCHIO GAMBA) DX </option>
<option value="49">TC DELL'ARTO INFERIORE (GINOCCHIO GAMBA) SX </option>
<option value="50">TC DELL'ARTO INFERIORE, SENZA E CON CONTRASTO (ART. COXOFEMORALE, FEMORE) DX </option>
<option value="51">TC DELL'ARTO INFERIORE, SENZA E CON CONTRASTO (ART. COXOFEMORALE, FEMORE) SX </option>
<option value="52">TC DELL'ARTO INFERIORE, SENZA E CON CONTRASTO (CAVIGLIA PIEDE) DX </option>
<option value="53">TC DELL'ARTO INFERIORE, SENZA E CON CONTRASTO (CAVIGLIA PIEDE) SX </option>
<option value="54">TC DELL'ARTO INFERIORE, SENZA E CON CONTRASTO (GINOCCHIO GAMBA) DX </option>
<option value="55">TC DELL'ARTO INFERIORE, SENZA E CON CONTRASTO (GINOCCHIO GAMBA) SX </option>
<option value="56">TC DELL'ENCEFALO</option>
<option value="57">TC DELL'ENCEFALO, SENZA E CON CONTRASTO </option>
<option value="58">TC DELL'ORECCHIO MEDIO E INTERNO </option>
<option value="59">TC DELL'ORECCHIO, SENZA E CON CONTRASTO BASE CRANICA E ANGOLO PONTO </option>
<option value="60">TC DELL'ORECCHIO, SENZA E CON CONTRASTO ORECCHIO MEDIO E INTERNO </option>
<option value="61">TC DELL'ORECCHIO, SENZA E CON CONTRASTO ROCCHE PETROSE E MASTOIDE </option>
<option value="62">TC DELLA BASE CRANICA E ANGOLO PONTO </option>
<option value="63">TC DELLA SPALLA E BRACCIO DX </option>
<option value="64">TC DELLA SPALLA E BRACCIO DX, SENZA E CON CONTRASTO </option>
<option value="65">TC DELLA SPALLA E BRACCIO SX </option>
<option value="66">TC DELLA SPALLA E BRACCIO SX, SENZA E CON CONTRASTO </option>
<option value="67">TC DELLE ARCATE DENTARIE [DENTALSCAN]</option>
<option value="68">TC DELLE GHIANDOLE SALIVARI</option>
<option value="69">TC DELLE ROCCHE PETROSE E MASTOIDE </option>
<option value="70">TC RACHIDE E SPECO VERTEBRALE</option>
<option value="71">TC RACHIDE E SPECO VERTEBRALE (Spazio intersomatico o metamero aggiuntivo in corso di TC del rachide)</option>
<option value="72">TORACENTESI TC GUIDATA</option>
<option value="73">EVENTUALE TOMOGRAFIA CONTEMP.AD ESAME DI</option>
<option value="74">TOMOGRAFIA [STRATIGRAFIA] BASALE E DINAMICA BILATERALE DI ARTICOLAZIONE TEMPOROMANDIBOLARE</option>
<option value="75">TOMOGRAFIA [STRATIGRAFIA] BILATERALE DI ARTICOLAZIONE TEMPOROMANDIBOLARE</option>
<option value="76">TOMOGRAFIA [STRATIGRAFIA] DEL MEDIASTINO</option>
<option value="77">TOMOGRAFIA [STRATIGRAFIA] DELLA LARINGE</option>
<option value="78">TOMOGRAFIA [STRATIGRAFIA] DELLE ARCATE DENTARIE</option>
<option value="79">TOMOGRAFIA [STRATIGRAFIA] DI SEGMENTO SCHELETRICO</option>
<option value="80">TOMOGRAFIA [STRATIGRAFIA] MONOLATERALE DI ARTICOLAZIONE TEMPOROMANDIBOLARE</option>
<option value="81">TOMOGRAFIA [STRATIGRAFIA] RENALE</option>
<option value="82">TOMOGRAFIA [STRATIGRAFIA] TORACICA BILATERALE</option>
<option value="83">TOMOGRAFIA [STRATIGRAFIA] TORACICA DX </option>
<option value="84">TOMOGRAFIA [STRATIGRAFIA] TORACICA MONOLATERALE</option>
<option value="85">TOMOGRAFIA [STRATIGRAFIA] TORACICA SX </option>
